export const generalTips: readonly string[] = [
  'Keep your back neutral on every rep. A tidy rep beats a heavy rep.',
  'Sip water between sets. Even mild dehydration makes lifting feel harder.',
  'Progressive overload is simple: a little more weight, a rep or a set than last time.',
  'A deload week every 4 to 8 weeks lets your body soak up all that hard work.',
  'Control the lowering part of each rep. Slow negatives build strength.',
  'Drink a glass of water when you wake up. Your gym session will thank you.',
  'Add one rep to each set before you add weight. Small steps add up.',
  'Warm up with a couple of light sets before your first heavy lift.',
  'Sleep is where the gains happen. Aim for 7 to 9 hours.',
  'Breathe out on the effort, breathe in on the way back. Never hold your breath for long.',
  'Feeling run down for a week? That is a good time for a deload.',
  'Track every set. What gets measured gets improved.',
  'Keep your knees tracking over your toes when you squat.',
  'Carry a water bottle to the gym and finish it before you leave.',
  'Lift the same weight with better form and you have still made progress.',
  'A deload means lighter weights, not skipping the gym. Keep the habit going.',
  'Rest 2 to 3 minutes between heavy sets so every set counts.',
  'Brace your core before each big lift, like you are about to take a gentle punch.',
  'Overload does not have to be weight. More reps, more sets or less rest all count.',
  'Thirsty means you are already a little behind. Drink steadily through the day.',
];
